# Generated by Django 5.2.7 on 2025-10-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='tipo',
            field=models.CharField(choices=[('serie', 'Série'), ('filme', 'Filme')], default='filme', max_length=10),
        ),
    ]
