# Generated by Django 5.2.7 on 2025-10-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroassistido',
            name='data_assistido',
            field=models.DateField(auto_now_add=True),
        ),
    ]
