# Generated by Django 5.2.7 on 2025-10-27 16:24

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0002_alter_registroassistido_data_assistido'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='registroassistido',
            name='data_assistido',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
